# Generated by Django 3.0 on 2020-01-08 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=100)),
                ('booked', models.BooleanField(default=False)),
                ('option', models.CharField(choices=[('1 single', '1 single bed in 1 room'), ('2 single', '2 single bed in 1 room'), ('1 double', '1 double bed in 1 room'), ('2 double', '2 double bed in 1 room'), ('4 single', '4 single bed in 1 room'), ('4 double', '4 double bed in 1 room')], default='1', max_length=100)),
                ('safe_off', models.BooleanField(default=False)),
                ('time_check_in', models.DateTimeField()),
                ('time_check_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/')),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
        ),
    ]
