# Generated by Django 3.0 on 2020-01-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='time_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='time_check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
