# Generated by Django 3.0.3 on 2020-02-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200205_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to='hotels/'),
        ),
    ]
