# Generated by Django 3.0 on 2020-01-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200108_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_safe_off',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=100),
        ),
    ]
