# Generated by Django 3.0.3 on 2020-02-05 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'slug')},
        ),
    ]
