# Generated by Django 3.0.3 on 2020-02-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200205_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
